### PR TITLE
Replace TravisCI with GitHub Actions

### LINKED ISSUE #12: Replace Travis-CI with GHA
Travis is MIA

### PR DESCRIPTION
**Pull request by duffn**
This mimics the Travis pipeline as close as I could, somewhat arbitrarily picking Mongo 4.0 as I couldn't find that noted anywhere.

Example run here: https://github.com/duffn/slack-ruby-bot-server-stripe-sample/actions/runs/2477812442

Closes #12

### CODE REVIEW

**Comment by dblock** [comment]
Thanks! Let's simplify this a bit. Take a look at https://github.com/dblock/slack-sup/blob/master/.github/workflows/test.yml that uses some plugins for Geckodriver and such? Use MongoDB 5.0.

**Comment by duffn** [comment]
Yeah, that's better, thanks for the example. Updated.

**Comment by dblock** [comment]
Merged, really appreciate you doing this, thanks!

**Comment by dblock** [comment]
@duffn if you have cycles, there are other projects in this org that could use the same ❤️

**Comment by duffn** [comment]
Sure, I saw a few others. I can take a look.

**Pull request merged**
